### ISSUE TITLE
Persist certs/keys after initial build

### ISSUE THREAD

**Issue by drywheat** [xhost-cookbooks/openvpn#71] opened 2015-11-28 23:44 UTC
Executing the `openvpn::default` on a new server will generate a slew of openssl files (i.e. server.crt, server.key, ca.crt, dh2048.pem, etc...). After the initial build of a VPN server and distribution of some of those files to clients, how do we ensure those files persist beyond node failure, or are used on say multiple openvpn servers (load balanced for availability)?

I must be missing something here.

**Comment by flaccid** [comment] 2016-02-21 09:08
@drywheat pretty sure this is just a straight duplicate of https://github.com/xhost-cookbooks/openvpn/issues/68. We need to cover persistence of stateful data for at least the server. Many possible solutions however we need someone to contribute at least one for v3 :)

**Closed by flaccid** 2016-02-21 09:08 UTC
Labels: question
